
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import UserProvider from "./context/user";
import { Providers } from "./providers";
import { MainNavbar } from "@/lib/components/ui/Navbar";
import { GoogleOAuthProvider } from "@react-oauth/google";
// import { NextUIProvider } from "@nextui-org/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GoogleOAuthProvider clientId="685021499038-do4c75sbl2p7vksobll2nmsc8ug24i5o.apps.googleusercontent.com">
        <Providers>
          <UserProvider>
            <MainNavbar />
            {children}
          </UserProvider>
        </Providers>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
